import { getDb } from "../api/queries/connection";
import { eq } from "drizzle-orm";
import {
  users,
  properties,
  propertyImages,
  locations,
  favorites,
  inquiries,
} from "./schema";

async function seed() {
  const db = getDb();

  // Seed locations
  const locationData = [
    { region: "Littoral", city: "Douala", neighborhood: "Bonapriso", displayName: "Bonapriso, Douala", listingCount: 24, imageUrl: "/loc-douala.jpg" },
    { region: "Littoral", city: "Douala", neighborhood: "Akwa", displayName: "Akwa, Douala", listingCount: 18, imageUrl: "/loc-douala.jpg" },
    { region: "Centre", city: "Yaoundé", neighborhood: "Bastos", displayName: "Bastos, Yaoundé", listingCount: 31, imageUrl: "/loc-yaounde.jpg" },
    { region: "Centre", city: "Yaoundé", neighborhood: "Essos", displayName: "Essos, Yaoundé", listingCount: 15, imageUrl: "/loc-yaounde.jpg" },
    { region: "South-West", city: "Buea", neighborhood: "Molyko", displayName: "Molyko, Buea", listingCount: 12, imageUrl: "/loc-buea.jpg" },
    { region: "North-West", city: "Bamenda", neighborhood: "Ntamulung", displayName: "Ntamulung, Bamenda", listingCount: 9, imageUrl: "/loc-bamenda.jpg" },
    { region: "West", city: "Bafoussam", neighborhood: "Toungang", displayName: "Toungang, Bafoussam", listingCount: 7, imageUrl: "/loc-bafoussam.jpg" },
    { region: "South-West", city: "Limbe", neighborhood: "Down Beach", displayName: "Down Beach, Limbe", listingCount: 11, imageUrl: "/loc-limbe.jpg" },
    { region: "North", city: "Garoua", neighborhood: "Centre Ville", displayName: "Centre Ville, Garoua", listingCount: 6, imageUrl: "/loc-garoua.jpg" },
    { region: "Far-North", city: "Maroua", neighborhood: "Domayo", displayName: "Domayo, Maroua", listingCount: 5, imageUrl: "/loc-maroua.jpg" },
  ];

  for (const loc of locationData) {
    await db.insert(locations).values(loc).onDuplicateKeyUpdate({
      set: { listingCount: loc.listingCount },
    });
  }

  // Seed a demo owner user if not exists
  const ownerUsers = await db.select().from(users).where(eq(users.email, "agent@bookam.cm"));
  let ownerId = 1;
  if (ownerUsers.length === 0) {
    const result = await db.insert(users).values({
      unionId: "demo_owner_001",
      name: "Jean-Paul Essomba",
      email: "agent@bookam.cm",
      phone: "+237 6 77 88 99 00",
      role: "user",
      city: "Douala",
      region: "Littoral",
      isVerifiedAgent: 1,
      bio: "Experienced real estate agent with 10+ years in Douala and Yaoundé markets. Specialized in luxury apartments and commercial properties.",
    }).$returningId();
    ownerId = result[0].id;
  } else {
    ownerId = ownerUsers[0].id;
  }

  // Seed properties
  const propertyData = [
    {
      title: "Modern 3-Bedroom Apartment in Bonapriso",
      description: "Beautiful modern apartment located in the heart of Bonapriso, Douala. Features spacious living room, fully equipped kitchen, 3 bedrooms with en-suite bathrooms, balcony with city view, 24/7 security, and underground parking. Perfect for families or professionals seeking comfort and convenience.",
      price: "450000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "apartment",
      status: "available",
      bedrooms: 3,
      bathrooms: 2,
      areaSqm: "145.00",
      furnished: 1,
      parking: 1,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "Littoral",
      city: "Douala",
      neighborhood: "Bonapriso",
      landmark: "Near Casino Supermarket",
      address: "Rue de la Joie, Bonapriso, Douala",
      amenities: JSON.stringify(["Air Conditioning", "WiFi", "Swimming Pool", "Gym", "Generator", "Security", "Parking"]),
      isFeatured: 1,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Luxury Villa with Garden in Bastos",
      description: "Stunning 5-bedroom villa in the prestigious Bastos neighborhood of Yaoundé. Large garden, swimming pool, guest house, modern kitchen, marble floors, and high-end finishes. Gated community with 24/7 security. Ideal for diplomats or large families.",
      price: "850000000.00",
      pricePeriod: "one_time",
      listingType: "sale",
      propertyType: "villa",
      status: "available",
      bedrooms: 5,
      bathrooms: 4,
      areaSqm: "650.00",
      furnished: 0,
      parking: 1,
      petFriendly: 1,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "Centre",
      city: "Yaoundé",
      neighborhood: "Bastos",
      landmark: "Near French Embassy",
      address: "Avenue des Ambassades, Bastos, Yaoundé",
      amenities: JSON.stringify(["Swimming Pool", "Garden", "Guest House", "Air Conditioning", "Generator", "Security", "Parking", "Solar Power"]),
      isFeatured: 1,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Cozy Studio Apartment in Molyko, Buea",
      description: "Affordable studio apartment perfect for students or young professionals. Located in Molyko, Buea near the university. Includes basic furniture, water heater, and reliable electricity. Close to shops and restaurants.",
      price: "75000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "studio",
      status: "available",
      bedrooms: 1,
      bathrooms: 1,
      areaSqm: "35.00",
      furnished: 1,
      parking: 0,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "South-West",
      city: "Buea",
      neighborhood: "Molyko",
      landmark: "Near University of Buea",
      address: "Molyko Main Street, Buea",
      amenities: JSON.stringify(["Water Heater", "Basic Furniture", "Study Desk"]),
      isFeatured: 0,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Commercial Office Space in Akwa",
      description: "Prime commercial office space in Akwa, Douala's business district. Open floor plan, meeting rooms, reception area, elevator access, and parking. High-speed internet ready. Perfect for startups or established businesses.",
      price: "350000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "office",
      status: "available",
      bedrooms: 0,
      bathrooms: 2,
      areaSqm: "200.00",
      furnished: 0,
      parking: 1,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "Littoral",
      city: "Douala",
      neighborhood: "Akwa",
      landmark: "Near Douala Central Market",
      address: "Boulevard de la Liberté, Akwa, Douala",
      amenities: JSON.stringify(["Elevator", "Meeting Rooms", "Reception", "Generator", "Security", "Parking"]),
      isFeatured: 1,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Family Home in Ntamulung, Bamenda",
      description: "Spacious family home in peaceful Ntamulung area of Bamenda. 4 bedrooms, large compound with fruit trees, garage, and outdoor kitchen. Quiet neighborhood with mountain views.",
      price: "180000000.00",
      pricePeriod: "one_time",
      listingType: "sale",
      propertyType: "house",
      status: "available",
      bedrooms: 4,
      bathrooms: 3,
      areaSqm: "400.00",
      furnished: 0,
      parking: 1,
      petFriendly: 1,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "North-West",
      city: "Bamenda",
      neighborhood: "Ntamulung",
      landmark: "Near Bamenda Hospital",
      address: "Ntamulung Quarter, Bamenda",
      amenities: JSON.stringify(["Garden", "Garage", "Outdoor Kitchen", "Mountain View"]),
      isFeatured: 0,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Beachfront Land in Down Beach, Limbe",
      description: "Prime beachfront land for sale in Down Beach, Limbe. 1200 sqm with ocean views and road access. Perfect for hotel development or luxury residential project. Clear title documents.",
      price: "250000000.00",
      pricePeriod: "one_time",
      listingType: "sale",
      propertyType: "land",
      status: "available",
      bedrooms: 0,
      bathrooms: 0,
      areaSqm: "1200.00",
      furnished: 0,
      parking: 0,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "South-West",
      city: "Limbe",
      neighborhood: "Down Beach",
      landmark: "Near Limbe Botanical Garden",
      address: "Down Beach Road, Limbe",
      amenities: JSON.stringify(["Beach Access", "Road Access", "Ocean View", "Clear Title"]),
      isFeatured: 1,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Affordable 2-Bedroom in Essos, Yaoundé",
      description: "Well-maintained 2-bedroom apartment in Essos, Yaoundé. Clean environment, good neighbors, proximity to public transport and markets. Great for small families or working couples.",
      price: "150000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "apartment",
      status: "available",
      bedrooms: 2,
      bathrooms: 1,
      areaSqm: "80.00",
      furnished: 0,
      parking: 0,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "Centre",
      city: "Yaoundé",
      neighborhood: "Essos",
      landmark: "Near Essos Market",
      address: "Rue Essos, Yaoundé",
      amenities: JSON.stringify(["Close to Market", "Public Transport", "Security"]),
      isFeatured: 0,
      isVerified: 0,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Newly Built Apartments in Toungang, Bafoussam",
      description: "Brand new apartment complex in Toungang, Bafoussam. Modern design, tiled floors, fitted kitchen, parking space, and reliable water supply. Multiple units available.",
      price: "120000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "apartment",
      status: "available",
      bedrooms: 2,
      bathrooms: 1,
      areaSqm: "75.00",
      furnished: 0,
      parking: 1,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "West",
      city: "Bafoussam",
      neighborhood: "Toungang",
      landmark: "Near Bafoussam Cathedral",
      address: "Toungang, Bafoussam",
      amenities: JSON.stringify(["New Construction", "Fitted Kitchen", "Parking", "Tiled Floors"]),
      isFeatured: 0,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Retail Shop in Centre Ville, Garoua",
      description: "High-traffic retail shop space in Centre Ville, Garoua. Ground floor, large display windows, storage room at back. Ideal for electronics, clothing, or general store.",
      price: "80000.00",
      pricePeriod: "monthly",
      listingType: "rent",
      propertyType: "commercial",
      status: "available",
      bedrooms: 0,
      bathrooms: 1,
      areaSqm: "60.00",
      furnished: 0,
      parking: 0,
      petFriendly: 0,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "North",
      city: "Garoua",
      neighborhood: "Centre Ville",
      landmark: "Near Garoua Main Market",
      address: "Centre Ville, Garoua",
      amenities: JSON.stringify(["High Traffic", "Display Windows", "Storage Room"]),
      isFeatured: 0,
      isVerified: 0,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
    {
      title: "Residential Compound in Domayo, Maroua",
      description: "Traditional yet well-maintained residential compound in Domayo, Maroua. 3 bedrooms, inner courtyard, external kitchen, and borehole water. Great for families looking for authentic northern Cameroon living.",
      price: "95000000.00",
      pricePeriod: "one_time",
      listingType: "sale",
      propertyType: "house",
      status: "available",
      bedrooms: 3,
      bathrooms: 2,
      areaSqm: "300.00",
      furnished: 0,
      parking: 1,
      petFriendly: 1,
      waterAvailable: 1,
      electricityAvailable: 1,
      region: "Far-North",
      city: "Maroua",
      neighborhood: "Domayo",
      landmark: "Near Maroua Grand Mosque",
      address: "Domayo Quarter, Maroua",
      amenities: JSON.stringify(["Courtyard", "Borehole", "External Kitchen", "Compound"]),
      isFeatured: 0,
      isVerified: 1,
      ownerId,
      contactPhone: "+237 6 77 88 99 00",
      contactEmail: "agent@bookam.cm",
    },
  ];

  for (const prop of propertyData) {
    const existing = await db.select().from(properties).where(eq(properties.title, prop.title));
    if (existing.length > 0) continue;

    const [{ id: propertyId }] = await db.insert(properties).values(prop as any).$returningId();

    // Insert images for each property
    const images = [
      { url: `https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop`, order: 0, isPrimary: 1 },
      { url: `https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop`, order: 1, isPrimary: 0 },
      { url: `https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop`, order: 2, isPrimary: 0 },
    ];

    for (const img of images) {
      await db.insert(propertyImages).values({ ...img, propertyId });
    }
  }

  console.log("Seed completed successfully!");
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});

